language: c

before_install:
    - sudo apt-get install python-software-properties 
    - sudo apt-add-repository -y ppa:libreoffice/libreoffice-4-2
    - sudo apt-get update
    - sudo apt-get install doxygen

after_success: 
    - travis-doygen.sh
